apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-interlace-controller
  template:
    metadata:
      labels:
        app: argocd-interlace-controller
    spec:
      serviceAccountName: argocd-interlace-controller
      containers:
        - name: argocd-interlace-controller
          image: ghcr.io/argoproj-labs/argocd-interlace-controller:dev
          imagePullPolicy: Always
          command:
            - argocd-interlace
          volumeMounts:
            - name: interlace-keys
              mountPath: /etc/keys
            - name: argocd-config
              mountPath: /etc/config
      volumes:
        - name: interlace-keys
          secret:
            secretName: argocd-interlace-keys
        - name: argocd-config
          secret:
            secretName: argocd-config-secret
