apiVersion: v1
kind: Secret
metadata:
    name: signing-secrets
    namespace: argocd-interlace
type: Opaque    
data:
   cosign.key: UkVQTEFDRSBUSElTCg==
   cosign.pub: UkVQTEFDRSBUSElTCg==

---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-token-secret
    namespace: argocd-interlace
type: Opaque    
data:
   ARGOCD_API_BASE_URL: UkVQTEFDRSBUSElTCg==
   ARGOCD_NAMESPACE: YXJnb2NkCg==
   ARGOCD_TOKEN: UkVQTEFDRSBUSElTCg==

