apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: applicationprovenances.interlace.argocd.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: interlace.argocd.dev
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                application:
                  type: object
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: applicationprovenances
    # singular name to be used as an alias on the CLI and for display
    singular: applicationprovenance
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ApplicationProvenance
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - appprov
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: interlaceprofiles.interlace.argocd.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: interlace.argocd.dev
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                applicationSelector:
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  type: array
                verifyConfig:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                signConfig:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                provenanceConfig:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: interlaceprofiles
    # singular name to be used as an alias on the CLI and for display
    singular: interlaceprofile
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: InterlaceProfile
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - iprof