apiVersion: v1
kind: Namespace
metadata:
  name: argocd-interlace
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationprovenances.interlace.argocd.dev
spec:
  group: interlace.argocd.dev
  names:
    kind: ApplicationProvenance
    plural: applicationprovenances
    shortNames:
    - appprov
    singular: applicationprovenance
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              application:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-interlace-controller
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - interlace.argocd.dev
  resources:
  - applicationprovenances
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-interlace-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-interlace-controller
subjects:
- kind: ServiceAccount
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: v1
data:
  private_key_pem: ""
kind: Secret
metadata:
  name: interlace-signing-key
  namespace: argocd-interlace
type: Opaque
---
apiVersion: v1
data:
  public_key_pem: ""
kind: Secret
metadata:
  name: source-material-verify-key
  namespace: argocd-interlace
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-interlace-controller
  template:
    metadata:
      labels:
        app: argocd-interlace-controller
    spec:
      containers:
      - command:
        - argocd-interlace
        env:
        - name: MANIFEST_STORAGE_TYPE
          value: resource
        - name: REKOR_SERVER
          value: https://rekor.sigstore.dev
        - name: SOURCE_MATERIAL_SIGNATURE
          value: source-materials.sig
        - name: SOURCE_MATERIAL_HASH_LIST
          value: source-materials
        - name: ALWAYS_GENERATE_PROV
          value: "true"
        - name: COSIGN_PASSWORD
          value: ""
        - name: MANIFEST_ARGOCD_PROJECT
          value: default
        - name: HELM_PLUGINS
          value: /root/.local/share/helm/plugins
        - name: SIGNATURE_RSC_LABEL
          value: signatureResource
        - name: MAX_RESULTS_IN_RESOURCE
          value: "10"
        - name: K8S_MANIFEST_SIGSTORE_LOG_LEVEL
          value: info
        - name: ARGOCD_INTERLACE_LOG_LEVEL
          value: info
        - name: ARGOCD_INTERLACE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ARGOCD_NAMESPACE
          value: argocd
        - name: ARGOCD_SERVER_SERVICE_NAME
          value: argocd-server
        - name: ARGOCD_USER_SECRET_NAME
          value: argocd-initial-admin-secret
        - name: ARGOCD_USER_SECRET_PASSFIELD
          value: password
        image: ghcr.io/argoproj-labs/argocd-interlace-controller:v0.2.0
        imagePullPolicy: Always
        name: argocd-interlace-controller
        volumeMounts:
        - mountPath: /etc/signkey
          name: sign-key
        - mountPath: /etc/verifykey
          name: verify-key
      serviceAccountName: argocd-interlace-controller
      volumes:
      - name: sign-key
        secret:
          secretName: interlace-signing-key
      - name: verify-key
        secret:
          secretName: source-material-verify-key
