apiVersion: v1
kind: Namespace
metadata:
  name: argocd-interlace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-interlace-controller-tenant-access
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-interlace-controller-tenant-access
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-interlace-controller-tenant-access
subjects:
- kind: ServiceAccount
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: v1
data:
  pubring.gpg: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: keyring-secret
  namespace: argocd-interlace
type: Opaque
---
apiVersion: v1
data:
  ARGOCD_API_BASE_URL: UkVQTEFDRSBUSElTCg==
  ARGOCD_NAMESPACE: YXJnb2NkCg==
  ARGOCD_TOKEN: UkVQTEFDRSBUSElTCg==
  ARGOCD_PWD: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: argocd-token-secret
  namespace: argocd-interlace
type: Opaque
---
apiVersion: v1
data:
  cosign.key: UkVQTEFDRSBUSElTCg==
  cosign.pub: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: signing-secrets
  namespace: argocd-interlace
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-interlace-controller
  template:
    metadata:
      labels:
        app: argocd-interlace-controller
    spec:
      containers:
      - args:
        - --namespace=argocd
        command:
        - argocd-interlace
        env:
        - name: DOCKER_CONFIG
          value: /tmp/.docker/
        - name: MANIFEST_STORAGE_TYPE
          value: annotation
        - name: REKOR_SERVER
          value: https://rekor.sigstore.dev
        - name: SOURCE_MATERIAL_SIGNATURE
          value: source-materials.sig
        - name: SOURCE_MATERIAL_HASH_LIST
          value: source-materials
        - name: ALWAYS_GENERATE_PROV
          value: "true"
        - name: COSIGN_PASSWORD
          value: ""
        - name: MANIFEST_ARGOCD_PROJECT
          value: default
        - name: K8S_MANIFEST_SIGSTORE_LOG_LEVEL
          value: info
        - name: ARGOCD_INTERLACE_LOG_LEVEL
          value: info
        - name: ARGOCD_NAMESPACE
          valueFrom:
            secretKeyRef:
              key: ARGOCD_NAMESPACE
              name: argocd-token-secret
        - name: ARGOCD_API_BASE_URL
          valueFrom:
            secretKeyRef:
              key: ARGOCD_API_BASE_URL
              name: argocd-token-secret
        - name: ARGOCD_TOKEN
          valueFrom:
            secretKeyRef:
              key: ARGOCD_TOKEN
              name: argocd-token-secret
        - name: ARGOCD_PWD
          valueFrom:
            secretKeyRef:
              key: ARGOCD_PWD
              name: argocd-token-secret
        image: quay.io/gajananan/argocd-interlace-controller:dev
        imagePullPolicy: Always
        name: argocd-interlace-controller
        volumeMounts:
        - mountPath: /tmp/output
          name: output
        - mountPath: /etc/signing-secrets
          name: signing-secrets
        - mountPath: /etc/keyring-secret
          name: keyring-secret
      serviceAccountName: argocd-interlace-controller
      volumes:
      - name: signing-secrets
        secret:
          secretName: signing-secrets
      - name: keyring-secret
        secret:
          secretName: keyring-secret
      - emptyDir: {}
        name: output

