apiVersion: v1
kind: Namespace
metadata:
  name: argocd-interlace
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationprovenances.interlace.argocd.dev
spec:
  group: interlace.argocd.dev
  names:
    kind: ApplicationProvenance
    plural: applicationprovenances
    shortNames:
    - appprov
    singular: applicationprovenance
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              application:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-interlace-controller
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - interlace.argocd.dev
  resources:
  - applicationprovenances
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-interlace-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-interlace-controller
subjects:
- kind: ServiceAccount
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: v1
data:
  argocdAPIPassword: UkVQTEFDRSBUSElTCg==
  argocdAPIUsername: UkVQTEFDRSBUSElTCg==
  argocdNamespace: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: argocd-config-secret
  namespace: argocd-interlace
type: Opaque
---
apiVersion: v1
data:
  signKey: UkVQTEFDRSBUSElTCg==
  verifyKey: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: argocd-interlace-keys
  namespace: argocd-interlace
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-interlace-controller
  template:
    metadata:
      labels:
        app: argocd-interlace-controller
    spec:
      containers:
      - command:
        - argocd-interlace
        env:
        - name: DOCKER_CONFIG
          value: /tmp/.docker/
        - name: TUF_ROOT
          value: /tmp/.sigstore
        - name: MANIFEST_STORAGE_TYPE
          value: annotation
        - name: REKOR_SERVER
          value: https://rekor.sigstore.dev
        - name: SOURCE_MATERIAL_SIGNATURE
          value: source-materials.sig
        - name: SOURCE_MATERIAL_HASH_LIST
          value: source-materials
        - name: ALWAYS_GENERATE_PROV
          value: "true"
        - name: COSIGN_PASSWORD
          value: ""
        - name: COSIGN_EXPERIMENTAL
          value: "1"
        - name: MANIFEST_ARGOCD_PROJECT
          value: default
        - name: SIGNATURE_RSC_LABEL
          value: integrityshield.io/signatureResource
        - name: K8S_MANIFEST_SIGSTORE_LOG_LEVEL
          value: info
        - name: ARGOCD_INTERLACE_LOG_LEVEL
          value: info
        - name: ARGOCD_INTERLACE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HELM_PLUGINS
          value: /root/.local/share/helm/plugins
        image: ghcr.io/argoproj-labs/argocd-interlace-controller:dev
        imagePullPolicy: Always
        name: argocd-interlace-controller
        volumeMounts:
        - mountPath: /tmp/output
          name: output
        - mountPath: /etc/keys
          name: interlace-keys
        - mountPath: /etc/config
          name: argocd-config
      serviceAccountName: argocd-interlace-controller
      volumes:
      - name: interlace-keys
        secret:
          secretName: argocd-interlace-keys
      - name: argocd-config
        secret:
          secretName: argocd-config-secret
      - emptyDir: {}
        name: output
